# Generated by Django 3.2.10 on 2022-01-07 09:30

from django.db import migrations, models
import django.db.models.deletion
import store.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس')),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='سر دسته')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتري')),
                ('family', models.CharField(max_length=200, verbose_name='نام خانوادگي مشتري')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='ايميل مشتري')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره تماس مشتري')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='آدرس مشتري')),
                ('refId', models.CharField(blank=True, max_length=100, verbose_name='كد پيگيري')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ثبت سفارش')),
                ('random_order_id', models.IntegerField(default=store.helper.random_int, unique=True, verbose_name=' شماره سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='توضيحات')),
                ('status', models.BooleanField(default=False, verbose_name='وضعيت')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='قيمت')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/product/images', verbose_name='تصوير')),
                ('category', models.ManyToManyField(blank=True, to='store.Category', verbose_name='دسته بندي')),
                ('recommended_product', models.ManyToManyField(blank=True, related_name='_store_product_recommended_product_+', to='store.Product', verbose_name='محصولات پيشنهادي')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='تعداد ')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='قيمت ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='نام سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='نام محصول')),
            ],
        ),
    ]
