# Generated by Django 3.2.10 on 2022-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Completed'), (2, 'Canceled'), (3, 'In progress'), (4, 'Checking'), (5, 'Paymentting')], default=4),
        ),
    ]
