# Generated by Django 3.2.10 on 2022-01-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('email', models.EmailField(max_length=200, verbose_name='ايميل')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='موبايل')),
                ('message', models.TextField(verbose_name='متن پيام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال پيام')),
            ],
        ),
    ]
