# Generated by Django 3.2.10 on 2022-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=50, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=50, verbose_name='تلفن همراه')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('copy_right', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
                ('logo_image', models.ImageField(blank=True, default='upload/images/no-img.jpg', null=True, upload_to='upload/images/images', verbose_name='تصویر لوگو')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس واتساپ')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس تلگرام')),
                ('twitter', models.CharField(blank=True, max_length=150, null=True, verbose_name=' آدرس توييتر')),
            ],
        ),
    ]
